// AUTO-GENERATED.
// Do not edit manually.
// Generated by scripts/build-geo-attribution.mjs from lib/commissions.ts,
// reconciled through lib/locationMap.ts. Every figure below is a count of rows
// in the commission record — nothing is authored.

export type PracticeAreaKey = "disputes" | "expert" | "advisory";

export type CountryAttribution = {
  m49: string;
  iso: string;
  name: string;
  /** false where the jurisdiction is counted but deliberately not drawn. */
  render: boolean;
  total: number;
  byArea: Record<PracticeAreaKey, number>;
  forums: string[];
  roles: string[];
};

export const AREA_LABELS: Record<PracticeAreaKey, string> = {
  "disputes": "Claims & Disputes",
  "expert": "Expert Witness",
  "advisory": "Project Advisory"
};

export const OVERALL = {
  "commissions": 276,
  "jurisdictions": 28,
  "byArea": {
    "disputes": 131,
    "expert": 76,
    "advisory": 69
  }
};

/** Commissions whose recorded location is not a single jurisdiction. */
export const NON_JURISDICTIONAL: { source: string; reason: string; count: number }[] = [
  {
    "source": "Unknown",
    "reason": "Location not recorded in the commission data.",
    "count": 6
  },
  {
    "source": "Worldwide",
    "reason": "Global scope; no single jurisdiction.",
    "count": 3
  },
  {
    "source": "GCC",
    "reason": "Multi-state region, not a jurisdiction.",
    "count": 1
  },
  {
    "source": "North Sea",
    "reason": "Maritime area; no land jurisdiction.",
    "count": 1
  },
  {
    "source": "Caribbean",
    "reason": "Multi-state region, not a jurisdiction.",
    "count": 1
  }
];

export const geoAttribution: CountryAttribution[] = [
  {
    "m49": "826",
    "iso": "GB",
    "name": "United Kingdom",
    "render": true,
    "total": 125,
    "byArea": {
      "disputes": 75,
      "expert": 11,
      "advisory": 39
    },
    "forums": [
      "Adjudication",
      "Advisory",
      "Arbitration",
      "Litigation",
      "Project"
    ],
    "roles": [
      "Adjudicator",
      "Advisor",
      "Assistant Expert",
      "Assistant Quantum Expert",
      "Commercial Management",
      "Engineer",
      "Party Representative",
      "Planning Manager",
      "Project Management",
      "Quantum Expert"
    ]
  },
  {
    "m49": "784",
    "iso": "AE",
    "name": "United Arab Emirates",
    "render": true,
    "total": 52,
    "byArea": {
      "disputes": 18,
      "expert": 23,
      "advisory": 11
    },
    "forums": [
      "Advisory",
      "Arbitration",
      "Litigation",
      "Project"
    ],
    "roles": [
      "Advisor",
      "Assistant Delay Expert",
      "Assistant Quantum Expert",
      "Commercial Management",
      "Delay Expert",
      "Party Representative",
      "Planning Manager",
      "Quantum Expert",
      "Technical Expert"
    ]
  },
  {
    "m49": "634",
    "iso": "QA",
    "name": "Qatar",
    "render": true,
    "total": 33,
    "byArea": {
      "disputes": 13,
      "expert": 13,
      "advisory": 7
    },
    "forums": [
      "Advisory",
      "Arbitration",
      "Project"
    ],
    "roles": [
      "Advisor",
      "Assistant Delay Expert",
      "Assistant Quantum Expert",
      "Commercial Management",
      "Delay Expert",
      "Engineer",
      "Party Representative",
      "Planning Manager",
      "Project Management",
      "Technical Expert"
    ]
  },
  {
    "m49": "682",
    "iso": "SA",
    "name": "Saudi Arabia",
    "render": true,
    "total": 10,
    "byArea": {
      "disputes": 8,
      "expert": 1,
      "advisory": 1
    },
    "forums": [
      "Advisory",
      "Arbitration",
      "Project"
    ],
    "roles": [
      "Advisor",
      "Assistant Quantum Expert",
      "Commercial Management",
      "Party Representative"
    ]
  },
  {
    "m49": "504",
    "iso": "MA",
    "name": "Morocco",
    "render": true,
    "total": 8,
    "byArea": {
      "disputes": 3,
      "expert": 5,
      "advisory": 0
    },
    "forums": [
      "Adjudication",
      "Arbitration",
      "Expert Determination",
      "Project"
    ],
    "roles": [
      "Adjudicator",
      "Assistant Delay Expert",
      "Delay Expert",
      "Party Representative",
      "Quantum Expert"
    ]
  },
  {
    "m49": "512",
    "iso": "OM",
    "name": "Oman",
    "render": true,
    "total": 6,
    "byArea": {
      "disputes": 2,
      "expert": 4,
      "advisory": 0
    },
    "forums": [
      "Advisory",
      "Arbitration"
    ],
    "roles": [
      "Advisor",
      "Arbitrator",
      "Assistant Quantum Expert",
      "Delay Expert",
      "Quantum Expert"
    ]
  },
  {
    "m49": "208",
    "iso": "DK",
    "name": "Denmark",
    "render": true,
    "total": 3,
    "byArea": {
      "disputes": 1,
      "expert": 0,
      "advisory": 2
    },
    "forums": [
      "Advisory",
      "Project"
    ],
    "roles": [
      "Advisor",
      "Commercial Management",
      "Project Management"
    ]
  },
  {
    "m49": "036",
    "iso": "AU",
    "name": "Australia",
    "render": true,
    "total": 2,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 1
    },
    "forums": [
      "Arbitration",
      "Project"
    ],
    "roles": [
      "Project Management",
      "Technical Expert"
    ]
  },
  {
    "m49": "052",
    "iso": "BB",
    "name": "Barbados",
    "render": true,
    "total": 2,
    "byArea": {
      "disputes": 0,
      "expert": 2,
      "advisory": 0
    },
    "forums": [
      "Advisory",
      "Litigation"
    ],
    "roles": [
      "Assistant Quantum Expert"
    ]
  },
  {
    "m49": "398",
    "iso": "KZ",
    "name": "Kazakhstan",
    "render": true,
    "total": 2,
    "byArea": {
      "disputes": 1,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Advisory",
      "Arbitration"
    ],
    "roles": [
      "Advisor",
      "Assistant Delay Expert"
    ]
  },
  {
    "m49": "710",
    "iso": "ZA",
    "name": "South Africa",
    "render": true,
    "total": 2,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 1
    },
    "forums": [
      "Advisory",
      "Project"
    ],
    "roles": [
      "Commercial Management",
      "Quantum Expert"
    ]
  },
  {
    "m49": "144",
    "iso": "LK",
    "name": "Sri Lanka",
    "render": true,
    "total": 2,
    "byArea": {
      "disputes": 1,
      "expert": 0,
      "advisory": 1
    },
    "forums": [
      "Advisory",
      "Project"
    ],
    "roles": [
      "Advisor",
      "Engineer"
    ]
  },
  {
    "m49": "044",
    "iso": "BS",
    "name": "The Bahamas",
    "render": true,
    "total": 2,
    "byArea": {
      "disputes": 0,
      "expert": 0,
      "advisory": 2
    },
    "forums": [
      "Project"
    ],
    "roles": [
      "Engineer"
    ]
  },
  {
    "m49": "010",
    "iso": "AQ",
    "name": "Antarctica",
    "render": false,
    "total": 1,
    "byArea": {
      "disputes": 1,
      "expert": 0,
      "advisory": 0
    },
    "forums": [
      "Advisory"
    ],
    "roles": [
      "Advisor"
    ]
  },
  {
    "m49": "048",
    "iso": "BH",
    "name": "Bahrain",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Arbitration"
    ],
    "roles": [
      "Technical Expert"
    ]
  },
  {
    "m49": "124",
    "iso": "CA",
    "name": "Canada",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Expert Determination"
    ],
    "roles": [
      "Quantum Expert"
    ]
  },
  {
    "m49": "818",
    "iso": "EG",
    "name": "Egypt",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Arbitration"
    ],
    "roles": [
      "Assistant Quantum Expert"
    ]
  },
  {
    "m49": "246",
    "iso": "FI",
    "name": "Finland",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Arbitration"
    ],
    "roles": [
      "Assistant Delay Expert"
    ]
  },
  {
    "m49": "276",
    "iso": "DE",
    "name": "Germany",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 1,
      "expert": 0,
      "advisory": 0
    },
    "forums": [
      "Advisory"
    ],
    "roles": [
      "Advisor"
    ]
  },
  {
    "m49": "831",
    "iso": "GG",
    "name": "Guernsey",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Litigation"
    ],
    "roles": [
      "Quantum Expert"
    ]
  },
  {
    "m49": "368",
    "iso": "IQ",
    "name": "Iraq",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Advisory"
    ],
    "roles": [
      "Assistant Delay Expert"
    ]
  },
  {
    "m49": "376",
    "iso": "IL",
    "name": "Israel",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Arbitration"
    ],
    "roles": [
      "Delay Expert"
    ]
  },
  {
    "m49": "524",
    "iso": "NP",
    "name": "Nepal",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 1,
      "expert": 0,
      "advisory": 0
    },
    "forums": [
      "Advisory"
    ],
    "roles": [
      "Advisor"
    ]
  },
  {
    "m49": "566",
    "iso": "NG",
    "name": "Nigeria",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Litigation"
    ],
    "roles": [
      "Assistant Quantum Expert"
    ]
  },
  {
    "m49": "616",
    "iso": "PL",
    "name": "Poland",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Litigation"
    ],
    "roles": [
      "Assistant Quantum Expert"
    ]
  },
  {
    "m49": "643",
    "iso": "RU",
    "name": "Russia",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Arbitration"
    ],
    "roles": [
      "Quantum Expert"
    ]
  },
  {
    "m49": "752",
    "iso": "SE",
    "name": "Sweden",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Advisory"
    ],
    "roles": [
      "Technical Expert"
    ]
  },
  {
    "m49": "792",
    "iso": "TR",
    "name": "Turkey",
    "render": true,
    "total": 1,
    "byArea": {
      "disputes": 0,
      "expert": 1,
      "advisory": 0
    },
    "forums": [
      "Advisory"
    ],
    "roles": [
      "Assistant Delay Expert"
    ]
  }
];

/** m49 codes drawn as active on the map. */
export const ACTIVE_M49: string[] = ["826","784","634","682","504","512","208","036","052","398","710","144","044","048","124","818","246","276","831","368","376","524","566","616","643","752","792"];
